[package]
edition = "2024"
name = "gencrypt"
version = "0.11.1"
description = "Personal usage hashing utility."
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = 0
panic = "abort"
incremental = false
strip = true

[dependencies]
tokio = { version = "1.52.3", default-features = false, features = ["rt-multi-thread", "macros"] }
aes-gcm = { version = "0.10.3", features = ["aes"] }
arboard = "3.6.1"
base64 = "0.22.1"
iced = { version = "0.14.0", features = ["tokio"] }
rand = "0.10.1"
zstd = "0.13.3"
rfd = "0.17.2"
mimalloc = { version = "0.1.52", features = ["secure"] }
argon2 = "0.5.3"
pqcrypto-mlkem = "0.1.1"
pqcrypto-traits = "0.3.5"
